### ISSUE TITLE
Improve staff design for the about page

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#118]
## Description
Improve staff component design
## Screenshots
Design
![image](https://user-images.githubusercontent.com/3693563/47071878-5b178800-d1fd-11e8-98e8-d56522db8788.png)

 
Current Implementation
![image](https://user-images.githubusercontent.com/3693563/47071914-75e9fc80-d1fd-11e8-831f-3af723b6eb1c.png)

## Tasks

- [x] Use `Monsterrat bold` for heading and titles instead of `Anton Regular` for a cleaner look
- [x] Add padding top and bottom for the staff section
- [x] Add padding right and left  to center the component to page
