### ISSUE TITLE
Improve the header typography for all pages

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#120]
## Description
Match the typography of the header component to the designs 

#### Design

*About page*
![image](https://user-images.githubusercontent.com/3693563/47072872-ac287b80-d1ff-11e8-9d0f-2776a9a51cb1.png)

*Join Network*
![image](https://user-images.githubusercontent.com/3693563/47089310-3b965480-d229-11e8-8db0-c1db5b9d078a.png)

*How sensors work*
![image](https://user-images.githubusercontent.com/3693563/47089339-4e108e00-d229-11e8-81af-cac9ac28fb88.png)

#### Implementation
About page
![image](https://user-images.githubusercontent.com/3693563/47073021-ff9ac980-d1ff-11e8-9020-b3feabd47c22.png)

*How sensors work*
![image](https://user-images.githubusercontent.com/3693563/47089428-81ebb380-d229-11e8-80e1-2fc133aa12a7.png)

*Join Network*
![image](https://user-images.githubusercontent.com/3693563/47089435-84e6a400-d229-11e8-8c1c-c2310d5e5874.png)

## Tasks
- [x] Match the typography to the design 
- [x] Remove the right and left padding of the text grid
- [x] Put text in a `<Grid item xs={8}/>` instead of padding
