### ISSUE TITLE
Fix the call to action component

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#126]
## Description
Improve the call to action cards

#### Design
![image](https://user-images.githubusercontent.com/3693563/47097429-10683100-d23a-11e8-877e-00ebaa9c9d5a.png)

#### Implementation
![image](https://user-images.githubusercontent.com/3693563/47097293-c4b58780-d239-11e8-815b-507d18ef7fe0.png)

## Tasks
- [x] Center cards
- [x] Reduce width of card
- [ ] Reduce height of card
- [x] Increase height to include buttons
