### ISSUE TITLE
Improve quality statistic component

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#130]
## Description
Improve component to match the designs

#### Design 
![image](https://user-images.githubusercontent.com/3693563/47099932-072d9300-d23f-11e8-9d62-bfeb92b7105b.png)

#### Current Implementation
![image](https://user-images.githubusercontent.com/3693563/47099956-13195500-d23f-11e8-828a-71d36db1a4a2.png)

## Tasks
- [x] Update font typography for all headings and titles
- [x] Center main Grid
- [x] Grid Background should be ` #fff `
- [x] Remove` border bottom ` for the last table cell
