### ISSUE TITLE
Improve the support section of the about page

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#18]
## Description
Improve the cards to match the sensors.AFRICA designs 

## Screenshots

Current
![image](https://user-images.githubusercontent.com/3693563/44844665-361e8400-ac54-11e8-90d1-751fa8578398.png)

Expected look:
![image](https://user-images.githubusercontent.com/3693563/44844753-741ba800-ac54-11e8-8f57-2deeb6ee47a8.png)

## Tasks
- [x] Remove unnecessary node component
- [x] Make content same height
- [x] Match button colors to the design CI
