### ISSUE TITLE
Create component for the sensors.AFRICA air landing page

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#20]
## Description
Create a new component for the issues section of the air landing page

## Screenshots

![image](https://user-images.githubusercontent.com/3693563/44847558-8a2d6680-ac5c-11e8-9f31-7f8a5e25efda.png)

## Tasks.
- [x] Add text section
- [x] Add percentage circle images
- [x] Center the grid
