### ISSUE TITLE
Create indoor and outdoor pollution component 

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#21]
## Description
Create a new component for the indoor and outdoor pollution section for the air landing page

## Screenshots
![image](https://user-images.githubusercontent.com/3693563/44847646-d37db600-ac5c-11e8-8d4b-c03d12eff8fa.png)

## Tasks 
- [ ] Create cards sections
- [ ] Center cards using flexbox
- [ ] Add text content 
- [ ] Add  buttons
