### ISSUE TITLE
Create how sensors work page

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#22]
## Description
Add how sensors work parent component page in the *pages / air* directory

## Screenshots
![image](https://user-images.githubusercontent.com/3693563/44848139-5b17f480-ac5e-11e8-99b2-cc7d8ed16b81.png)

## Tasks
- [x] Add navbar component
- [x] Add main header section
- [x] Add hardware info component
- [x] Add footer section
