### ISSUE TITLE
Add hardware info component for the how sensors work page

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#23]
## Description
Create a *hardwareInfo* component for the *how sensors works* page

## Screenshots

![image](https://user-images.githubusercontent.com/3693563/44848293-dda0b400-ac5e-11e8-8205-909d63922243.png)

## Tasks

- [x] Add sensors images to the asset folder
- [x] Use flexbox to create content grid sections
- [x] Add text and images to the content section
