### ISSUE TITLE
Create cards component for the airborne diseases page

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#26]
## Description
Create a card component for the climate effects content

## Screenshots
![image](https://user-images.githubusercontent.com/3693563/44848982-586ace80-ac61-11e8-9da5-80abc79878cc.png)

## Tasks
- [ ] Create Grid section
- [ ] Add cards with no margin
- [ ] Add card content as per the design

**Comment by kilemensi** [comment]
Already implemented
