### ISSUE TITLE
Create host sensors call to action section/component for the air city page

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#29]
## Description
Create a new component for the host sensors section 

## Screenshots

![image](https://user-images.githubusercontent.com/3693563/44850065-bf3db700-ac64-11e8-9b63-a2c1d193e305.png)

## Tasks
- [x] Add buttons 
- [x] Create two grid sections 
- [x] Add content for the call to action grid
- [ ] Add tweet grid section with content
