### ISSUE TITLE
Create measure statistics component for the air city page

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#33]
## Description
Add new component for the city page

## Screenshots
![image](https://user-images.githubusercontent.com/3693563/44850330-86521200-ac65-11e8-8b7a-5550c82082a4.png)

## Tasks
- [x] Create two grids `<Grid item xs={4}/>` and  ` <Grid item xs={8}/>`
- [x] Use material-ui tables for the data statistics 
- [x] Add buttons and subheading texts in the left grid
