### ISSUE TITLE
Add search bar on the air landing page

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#53]
## Description
Add search bar on the landing page of the air page.

## Screenshots
![image](https://user-images.githubusercontent.com/3693563/45430631-70edd680-b6ae-11e8-8f19-6952fb4c81a1.png)

## Tasks
- [x] Add search input form on the air landing page
- [x] Align search bar center 
- [x] Add handle event on click
