### ISSUE TITLE
Add functionality to all buttons and anchor links in v1.0

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#55]
## Description
Add event triggers to all buttons and anchor links in v.1.0

## Tasks

- [ ] Add events/states to the Footer
- [ ] Add events/states to the Support section
- [ ] Add events /states to Header section
