### ISSUE TITLE
Add sensors.AFRICA API to the site

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#58]
## Description
Add sensors.AFRICA API  to be used in the city page 

## Tasks
- [x] Yarn add axios.
- [x] Create an empty sensors array as the default state of the class component
- [x] Use `axios.get()` to fetch data and console .log the data for use in future components
