### ISSUE TITLE
Add header and footer components to the city page

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#60]
## Description
Add the Header and Footer global components to the city page

## Screenshot
Header component
![image](https://user-images.githubusercontent.com/3693563/45683400-28ba3280-bb4c-11e8-9d1f-c8f5f671672b.png)

Footer component
![image](https://user-images.githubusercontent.com/3693563/45683414-3a9bd580-bb4c-11e8-992e-71935883d9dd.png)

## Tasks
- [x] Add the navbar and the jumbotron header component
- [x] Customize the menubar section to look like the city page designs
- [x] Add the footer component
