### ISSUE TITLE
Fix the city page components

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#76]
## Description
Small fixes on the city page layout
## Screenshots
![image](https://user-images.githubusercontent.com/3693563/46128544-7a457a00-c23c-11e8-9c46-9dece03da71b.png)

## Tasks
- [x] Remove scrolling in the map component
- [x] Add margin to the measure statistics component
- [x] Center content of the measure statistic component
- [x] Add top border to the statistic report component
