### ISSUE TITLE
[BUG] Improve Homepage Design

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfricaLabs/sensors.AFRICA#89]
## Description
The current homepage needs to align closer to designs shared.

## Screenshots

<img width="1680" alt="screen shot 2018-10-11 at 14 58 48" src="https://user-images.githubusercontent.com/877919/46802527-3dae6e00-cd66-11e8-82ec-f4ba9e34d1f1.png">

## Tasks

- [x] 1. Lead text match content + font style and weight
- [x] 2. Update text to match content + font style and weight
- [x] 3. Match such that height is smaller than width
