### ISSUE TITLE
Create default pages

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfricaLabs/sensors.AFRICA#9]
## Description
To work on, let's create the default pages:
- Home
- About
- City Page

## Screenshots
N/A

## Files
N/A

## Tasks
- [x] Create home page
- [x] Create about page
- [x] Create city page
