### ISSUE TITLE
Fix footer partner image section 

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#90]
## Description
Partner images in the footer section are on separate rows for medium devices

## Screenshots
![image](https://user-images.githubusercontent.com/3693563/46802721-ce854980-cd66-11e8-9376-896735be0005.png)

## Tasks
- [x] Remove padding from main grid container
- [x] Add padding to support text
- [x] Remove unnecessary `Grid` container from the images section
