### ISSUE TITLE
Use charts for the percentage issues section

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#91]
## Description
Use chart visualisation instead of an image for pollution count

## Screenshots

![image](https://user-images.githubusercontent.com/3693563/46802864-4fdcdc00-cd67-11e8-98ae-e7a27ee99e29.png)

## Tasks
- [x] Create gauge chart component
- [ ] Style according to designed layout
- [ ] Write test for gauge component

**Comment by mtuchi** [comment]
@nerdlet 
I used this component incase you need some reference 
https://codepen.io/yomaswn/pen/GXGRoo
