### ISSUE TITLE
[BUG] Improve Footer Design

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfricaLabs/sensors.AFRICA#93]
## Description
Improve the footer design to be closer to PSDs

## Screenshots
<img width="1680" alt="screen shot 2018-10-11 at 15 05 59" src="https://user-images.githubusercontent.com/877919/46802853-4784a100-cd67-11e8-85de-4d051caac125.png">

## Tasks

- [ ] 1.1. Increase padding top and bottom - should also be equal so probably check if `<p>` applying a margin bottom (remove if so)
- [ ] 1.2. Increase padding left and right to make content "tighter"

- [ ] 2.1. Add instagram
- [ ] 2.2. Re-order: Twitter, Facebook, Instagram
- [ ] 2.3. Increase margin top and bottom of social icons
- [ ] 2.4. Add Medium link to 
https://medium.com/code-for-africa/tagged/innovateafrica

- [ ] 3.1. Match e-mail input design
- [ ] 3.2. [BUG] Doesn't actually work when e-mail input
- [ ] 3.3. Input should be placeholder instead of value

- [ ] 4.1. Increase button padding
- [ ] 4.2. Check font size and style

- [ ] 5.1. Read More should go to about page
- [ ] 5.2. Button style should match feedback for (4)

- [ ] 6.1. Also all footer titles - font style + size match to design

- [ ] 7.1. Size + images used should match https://sensors.africa/

- [ ] 8. Change "Support" to "Funded By"
