### ISSUE TITLE
[BUG] Improve Hamburger Menu design

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfricaLabs/sensors.AFRICA#96]
## Description
The hamburger menu design can be improved to match designs by doing the tasks below.

## Screenshots
<img width="1680" alt="screen shot 2018-10-11 at 16 05 45" src="https://user-images.githubusercontent.com/877919/46806164-959da280-cd6f-11e8-81bd-aefe2b73e4f0.png">

## Tasks

- [ ] 1. Logo should be above the modal
- [ ] 2.1. Right align menu items
- [ ] 2.2. Update font style + size
- [ ] 2.3. Menu items should be as in design
- [ ] 3. Close button should be above modal and menu items right aligned to it
