### ISSUE TITLE
[BUG] Improve landing page design implementation 

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfricaLabs/sensors.AFRICA#97]
## Description
Improve landing page design implementation.

## Screenshots
<img width="1680" alt="screen shot 2018-10-11 at 16 16 34" src="https://user-images.githubusercontent.com/877919/46806789-2de85700-cd71-11e8-9ca9-1b1dae6ae327.png">

## Tasks

- [x] 1.1. Font size + style update
- [x] 1.2. Remove shadow from navbar 

- [x] 2.1. Add instagram 
- [x] 2.2. Make icons same width
- [x] 2.3. Increase hamburger menu icon thickness

- [x] 3.1. Update font size + style
- [x] 3.2. Content should be same as in designs

- [x] 4. Update input box design to match designs
- [x] 5. Update dropdown to match designs
