### ISSUE TITLE
[BUG] Improve landing page stats section

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfricaLabs/sensors.AFRICA#98]
## Description
Improve landing page stats section design implementation .

## Screenshots

**Designs**
![sensors landing page-air 2 2](https://user-images.githubusercontent.com/877919/46807389-76ecdb00-cd72-11e8-81e8-c2bb85ed6689.png)

**Current**
<img width="1664" alt="screen shot 2018-10-11 at 16 23 44" src="https://user-images.githubusercontent.com/877919/46807387-76544480-cd72-11e8-8ffa-88937cba3357.png">

## Tasks

- [x] 1. Revisit font style, size etc for each of these pieces
- [x] 2.1. Reduce padding top and bottom
- [x] 2.2. Reduce icon size
- [x] 2.3. Revisit font style + size
- [x] 3. + 4. Revisit button padding + style to match designs
